// Test generated by RoostGPT for test AmiCorp using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.controller;

import com.bootexample4.products.model.Product;
import com.bootexample4.products.repository.ProductRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class ProductController_deleteProduct_dcaff736d4_Test {

    @InjectMocks
    private ProductController productController;

    @Mock
    private ProductRepository productRepository;

    private Product product;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        product = new Product();
        product.setId(1L);
    }

    @Test
    public void testDeleteProduct_Success() {
        Mockito.when(productRepository.findById(1L)).thenReturn(Optional.of(product));
        ResponseEntity<Object> responseEntity = productController.deleteProduct(1L);
        assertEquals(HttpStatus.OK, responseEntity.getStatusCode());
        Mockito.verify(productRepository, Mockito.times(1)).delete(product);
    }

    @Test
    public void testDeleteProduct_NotFound() {
        Mockito.when(productRepository.findById(1L)).thenReturn(Optional.empty());
        ResponseEntity<Object> responseEntity = productController.deleteProduct(1L);
        assertEquals(HttpStatus.NOT_FOUND, responseEntity.getStatusCode());
        Mockito.verify(productRepository, Mockito.times(0)).delete(product);
    }
}
