// Test generated by RoostGPT for test AmiCorp using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Assertions;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

public class Product_setId_04a8e16b7c_Test {

    @InjectMocks
    private Product product;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testSetId_PositiveNumber() {
        Long expectedId = 1L;
        product.setId(expectedId);
        Assertions.assertEquals(expectedId, product.getId());
    }

    @Test
    public void testSetId_Zero() {
        Long expectedId = 0L;
        product.setId(expectedId);
        Assertions.assertEquals(expectedId, product.getId());
    }

    @Test
    public void testSetId_Null() {
        Long expectedId = null;
        product.setId(expectedId);
        Assertions.assertEquals(expectedId, product.getId());
    }
}
