// Test generated by RoostGPT for test AmiCorp using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class Product_getName_8400ac6fb7_Test {

    private Product product;

    @BeforeEach
    public void setUp() {
        product = Mockito.mock(Product.class);
    }

    @Test
    public void testGetName_Success() {
        String expectedName = "Test Product";
        Mockito.when(product.getName()).thenReturn(expectedName);
        String actualName = product.getName();
        assertEquals(expectedName, actualName);
    }

    @Test
    public void testGetName_Empty() {
        String expectedName = "";
        Mockito.when(product.getName()).thenReturn(expectedName);
        String actualName = product.getName();
        assertEquals(expectedName, actualName);
    }

    @Test
    public void testGetName_Null() {
        Mockito.when(product.getName()).thenReturn(null);
        String actualName = product.getName();
        assertEquals(null, actualName);
    }
}
