// Test generated by RoostGPT for test AmiCorp using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_setDescription_b4ccff923c_Test {

    private Product product;

    @BeforeEach
    public void setUp() {
        product = new Product();
    }

    @Test
    public void testSetDescription_Success() {
        String description = "This is a test description";
        product.setDescription(description);
        assertEquals(description, product.getDescription());
    }

    @Test
    public void testSetDescription_Null() {
        product.setDescription(null);
        assertEquals(null, product.getDescription());
    }
}
