// Test generated by RoostGPT for test AmiCorp using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_setPrice_8f1e19b496_Test {

    @Mock
    private Product product;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
        product = new Product();
    }

    @Test
    public void testSetPrice_PositiveValue() {
        double expectedPrice = 100.0;
        product.setPrice(expectedPrice);
        assertEquals(expectedPrice, product.getPrice(), "The price should be set to the value provided");
    }

    @Test
    public void testSetPrice_ZeroValue() {
        double expectedPrice = 0.0;
        product.setPrice(expectedPrice);
        assertEquals(expectedPrice, product.getPrice(), "The price should be set to the value provided even if it's zero");
    }
}
